[build]
  publish = "public"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 